### get all messages
GET http://localhost:3000/api/messages HTTP/1.1
content-type: application/json


### add new message
POST http://localhost:3000/api/messages HTTP/1.1
content-type: application/json

{
  "message": {
    "content": "hello there",
    "messageType": "email",
    "sender": "math@testmath.com",
    "receiver": "mthldjanssen@gmail.com",
    "title": "test de mail"
  }
}